--1. 급여가 5000이상 12000이하인 사원의 아이디, 이름, 급여를 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 5000
AND SALARY <= 12000;
--2. 사원들이 소속된 부서의 부서명을 중복없이 조회하기
SELECT DISTINCT DEPARTMENT_NAME
FROM DEPARTMENTS;
--3. 2007년에 입사한 사원의 아이디, 이름, 입사일을 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE >= '2007/01/01'
AND HIRE_DATE <= '2007/12/31';
--4. 급여가 5000이상 12000이하이고, 20번과 50번 부서에 소속된 사원의 아이디, 이름, 급여, 소속부서명을 
--   조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 12000
AND DEPARTMENT_ID IN (20,50);
--5. 100직원에게 보고하는 사원의 아이디, 이름, 급여, 급여등급을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY, B.GRA
FROM EMPLOYEES A, JOB_GRADES B
WHERE MANAGER_ID = 100
AND A.SALARY >= B.LOWEST_SAL
AND A.SALARY <= B.HIGHEST_SAL;
--6. 80번 부서에 소속되어 있고, 80번 부서의 평균급여보다 적은 급여를 받는 사원의 아이디, 이름, 
--   급여를 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
FROM EMPLOYEES A, (SELECT DEPARTMENT_ID, TRUNC(AVG(SALARY)) AVGSAL
                   FROM EMPLOYEES
                   WHERE DEPARTMENT_ID = 80
                   GROUP BY DEPARTMENT_ID) B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
AND A.SALARY <= B.AVGSAL;
--7. 50번 부서에 소속된 사원 중에서 해당 직종의 최소급여보다 2배 이상의 급여를 받는 사원의 아이디, 
--   이름, 급여를 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
FROM EMPLOYEES A, JOBS B
WHERE A.JOB_ID = B.JOB_ID
AND DEPARTMENT_ID = 50
AND A.SALARY >= (B.MIN_SALARY*2);
--8. 사원들 중에서 자신의 상사보다 먼저 입사한 사원의 아이디, 이름, 입사일, 상사의 이름, 
--   상사의 입사일을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.HIRE_DATE, B.FIRST_NAME 상사의이름, B.HIRE_DATE 상사의입사일
FROM EMPLOYEES A, EMPLOYEES B
WHERE A.MANAGER_ID = B.EMPLOYEE_ID
AND A.HIRE_DATE < B.HIRE_DATE;
--9. Steven King과 같은 부서에서 근무하는 사원의 아이디와 이름을 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                       FROM EMPLOYEES
                       WHERE FIRST_NAME = 'Steven'
                       AND LAST_NAME = 'King');
--10. 관리자별 사원수를 조회하기, 관리자 아이디, 사원수를 출력한다. 관리자 아이디순으로 오름차순 정렬
SELECT MANAGER_ID, COUNT(*) AS 관리자별사원수
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
ORDER BY MANAGER_ID ASC;
--11. 커미션을 받는 사원의 아이디, 이름, 급여, 커미션을 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;
--12. 급여를 가장 많이 받는 사원 3명의 아이디, 이름, 급여를 조회하기
SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME, SALARY
FROM (SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
      FROM EMPLOYEES
      ORDER BY SALARY DESC)
WHERE ROWNUM<=3;
--13. 'Ismael'과 같은 해에 입사했고, 같은 부서에 근무하는 사원의 아이디, 이름, 입사일을 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = (SELECT TO_CHAR(HIRE_DATE, 'YYYY')
                                    FROM EMPLOYEES
                                    WHERE FIRST_NAME = 'Ismael')
AND DEPARTMENT_ID = (SELECT DEPARTMENT_ID
                     FROM EMPLOYEES
                     WHERE FIRST_NAME = 'Ismael');
--14. 'Renske'에게 보고받는 사원의 아이디와 이름, 급여, 급여 등급을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY, B.GRA
FROM EMPLOYEES A, JOB_GRADES B
WHERE A.MANAGER_ID = (SELECT EMPLOYEE_ID
                      FROM EMPLOYEES
                      WHERE FIRST_NAME = 'Renske')
AND A.SALARY >= B.LOWEST_SAL
AND A.SALARY <= B.HIGHEST_SAL;
--15. 사원테이블의 급여를 기준으로 급여등급을 조회했을 때, 급여등급별 사원수를 조회하기
SELECT B.GRA, COUNT(*)
FROM EMPLOYEES A, JOB_GRADES B
WHERE A.SALARY >= B.LOWEST_SAL
AND A.SALARY <= B.HIGHEST_SAL
GROUP BY B.GRA
ORDER BY B.GRA ASC;
--16. 입사자가 가장 적은 년도와 그 해에 입사한 사원수를 조회하기
SELECT MIN,CNT
FROM (SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS MIN,  COUNT(*) AS CNT
                                    FROM EMPLOYEES
                                    GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
                                    ORDER BY CNT ASC)
WHERE ROWNUM = 1;
--17. 관리자별 사원수를 조회했을 때 관리자하는 사원수가 10명을 넘는 관리자의 아이디와 사원수를 조회하기
SELECT A.EMPLOYEE_ID, B.CNT
FROM EMPLOYEES A, (SELECT MANAGER_ID, COUNT(*) CNT
                   FROM EMPLOYEES
                   WHERE MANAGER_ID IS NOT NULL
                   GROUP BY MANAGER_ID) B
WHERE A.EMPLOYEE_ID = B.MANAGER_ID
AND CNT >= 10;
--18. 'Europe'지역에서 근무중이 사원의 아이디, 이름, 소속부서명, 소재지 도시명, 나라이름을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, B.DEPARTMENT_NAME, C.CITY, D.COUNTRY_NAME
FROM EMPLOYEES A, DEPARTMENTS B, LOCATIONS C, COUNTRIES D, REGIONS E
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
AND B.LOCATION_ID = C.LOCATION_ID
AND C.COUNTRY_ID = D.COUNTRY_ID
AND D.REGION_ID = E.REGION_ID
AND E.REGION_NAME = 'Europe';
--19. 전체 사원의 사원아이디, 이름, 급여, 소속부서아이디, 소속부서명, 상사의 이름을 조회하기
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY, A.DEPARTMENT_ID, C.DEPARTMENT_NAME, B.FIRST_NAME 상사이름
FROM EMPLOYEES A, EMPLOYEES B, DEPARTMENTS C
WHERE A.DEPARTMENT_ID = C.DEPARTMENT_ID
AND A.MANAGER_ID = B.EMPLOYEE_ID;
--20. 50번 부서에 근무중이 사원들의 급여를 500달러 인상시키기
UPDATE EMPLOYEES
SET SALARY = SALARY + 500
WHERE DEPARTMENT_ID = 50;
--21. 사원의 아이디, 이름, 급여, 보너스를 조회하기,
--    보너스는 20000달러 이상은 급여의 10%, 10000달러 이상은 급여의 15%, 그 외는 급여의 20%를 지급한다.
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, CASE
    WHEN SALARY>=20000 THEN SALARY+(SALARY*0.1)
    WHEN SALARY>=10000 THEN SALARY+(SALARY*0.15)
    ELSE SALARY+(SALARY*0.2)
    END AS BONUS
FROM EMPLOYEES;
--22. 소속부서에서 입사일이 늦지만, 더 많은 급여를 받는 사원의 이름, 입사일, 소속부서명, 급여를 조회하기
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS;
--23. 부서별 평균급여를 조회했을 때 부서별 평균급여가 10000달러 이하인 부서의 아이디, 부서명, 평균급여를
--    조회하기 (평균급여는 소숫점 1자리까지만 표시)
SELECT B.DEPARTMENT_ID, B.DEPARTMENT_NAME, TRUNC(AVG(SALARY),1) AVG_SALARY
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
GROUP BY B.DEPARTMENT_NAME, B.DEPARTMENT_ID
HAVING AVG(SALARY) < 10000
ORDER BY B.DEPARTMENT_ID;
--24. 사원들 중에서 자신 종사하고 있는 직종의 최대급여와 동일한 급여를 받는 사원의 아이디, 이름, 급여를
--    조회하기
SELECT * FROM JOBS;
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY
FROM EMPLOYEES A, JOBS B
WHERE A.SALARY = B.MAX_SALARY
AND A.JOB_ID = B.JOB_ID;
----25. 분석함수를 사용해서 사원들을 급여순으로 정렬하고, 순번을 부여했을 때 6~10번째 속하는 순번,
--    사원의 아이디, 이름, 급여, 급여등급을 조회하기
SELECT NUM, EMPLOYEE_ID, FIRST_NAME, SALARY,GRA
FROM (SELECT ROW_NUMBER() OVER(ORDER BY SALARY DESC) NUM, A.EMPLOYEE_ID, A.FIRST_NAME, A.SALARY, B.GRA
      FROM EMPLOYEES A, JOB_GRADES B
      WHERE A.SALARY>=B.LOWEST_SAL
      AND A.SALARY <= B.HIGHEST_SAL)
WHERE NUM >= 6 AND NUM <=10;

